
PROJECT_CMD_CFG := cmd-cfg.mk
PROJECT_PRO_CFG := pro-cfg.mk
PROJECT_PRO_RULE := pro-rule.mk

DIR_PROJECT := $(realpath .)

#PROJECT_CMD_CFG := $(addprefix $(DIR_PROJECT)/,$(PROJECT_CMD_CFG))
#PROJECT_PRO_CFG := $(addprefix $(DIR_PROJECT)/,$(PROJECT_PRO_CFG))
#PROJECT_PRO_RULE := $(addprefix $(DIR_PROJECT)/,$(PROJECT_PRO_RULE))

include $(PROJECT_CMD_CFG)
include $(PROJECT_PRO_CFG)
include $(PROJECT_PRO_RULE)