


include $(MODULE_CFG)

#for specified path or suffix
#
#TYPE_OBJ := .o
#TYPE_SRC := .c
#TYPE_INC := .h
#TYPE_DEP := .d

#DIR_SRC := src
#DIR_INC := inc
#

include $(MODULE_CMD)

include $(MODULE_RULE)
	
	
	
	
	
	